

export const rows = [
  {
    id: 1,
    name: "Mohamed Hmid",
    email: "Mohamed3@gmail.com",
    etat: "-",
    phone: "061121-5454",
    access: "Admin",
  },
  {
    id: 2,
    name: "Zaid AIT AHMID",
    email: "Zaid14@gmail.com",
    etat: "-",
    phone: "061314-2288",
    access: "Admin",
  },
  {
    id: 3,
    name: "Driss Haddo",
    email: "Driss2@gmail.com",
    etat: "-",
    phone: "064982-6739",
    access: "Admin",
  },
  {
    id: 4,
    name: "Anas BOBOT",
    email: "Anasbobot@gmail.com",
    etat: "EN COURS",
    phone: "062425-6742",
    access: "Client",
  },
  {
    id: 5,
    name: "Amina FADOULI",
    email: "aminatata@gmail.com",
    etat: "TERMINE",
    phone: "061445-1189",
    access: "Client",
  },
  {
    id: 6,
    name: "Karima Hssini",
    email: "hssini@gmail.com",
    etat: "TERMINE",
    phone: "066545-6483",
    access: "Client",
  },
  {
    id: 7,
    name: "Jamal Kabbaj",
    email: "Kabbaj@gmail.com",
    etat: "EN COURS",
    phone: "061124-0123",
    access: "Client",
  },
  {
    id: 8,
    name: "Mounim CHADOH",
    email: "mounimchadoh@gmail.com",
    etat: "EN COURS",
    phone: "064444-5555",
    access: "Client",
  },
  {
    id: 9,
    name: "Salama ZYAD",
    email: "salamazyad@gmail.com",
    etat: "TERMINE",
    phone: "062555-6239",
    access: "Client",
  },
];

